generateBEASTGeoXML_HHS_subsamp <- function(clusterdata,season,subtype){
  
  generateSingleStrain <- function(taxon,date,state){print(state)
    return(paste0(
      "<taxon id='",taxon,"'>\n",
      "<date value='",date,
      "' direction='forwards' units='years' uncertainty='0.0'/>\n",
      "<attr name='state'>",state,"</attr>\n",
      "</taxon>\n"))}
  
  generateTaxa <- function(name,taxa,dates,states){
    taxa_xml = do.call(paste0,lapply(1:length(taxa),function(x)generateSingleStrain(taxa[x],dates[x],states[x])))
    taxa_xml = paste0("\n<taxa id = '",name,".taxa'>",taxa_xml)
    taxa_xml = paste0(taxa_xml,"</taxa>\n")
    
    return(taxa_xml)
  }
  
  generateHeader <- function(){
    return('<?xml version="1.0" standalone="yes"?>
    
    <!-- Generated by BEAUTi v1.10.4 Prerelease #bc6cbd9                         -->
  <!--       by Alexei J. Drummond, Andrew Rambaut and Marc A. Suchard         -->
    <!--       Department of Computer Science, University of Auckland and        -->
    <!--       Institute of Evolutionary Biology, University of Edinburgh        -->
    <!--       David Geffen School of Medicine, University of California, Los Angeles-->
    <!--       http://beast.community/                                           -->
    <beast version="1.10.4">')}
  
  
  generateTaxonSets <- function(names){
    str = ""
    
    for (i in 1:length(names)){
      
      str = paste0(str,gsub("tree1",names[[i]],'
	<generalDataType id="tree1.state.dataType">

		<state code="HHS1"/>
		<state code="HHS2"/>
		<state code="HHS3"/>
		<state code="HHS4"/>
		<state code="HHS5"/>
		<state code="HHS6"/>
		<state code="HHS7"/>
		<state code="HHS8"/>
		<state code="HHS9"/>
		<state code="HHS10"/>

	</generalDataType>


	<attributePatterns id="tree1.state.pattern" attribute="state">
		<taxa idref="tree1.taxa"/>
		<generalDataType idref="tree1.state.dataType"/>
	</attributePatterns>
               
               '))
    }
    return(str)
  }
  
  
  generateTreeModels <- function(names){
    str = '

	<empiricalTreeDistributionModel id="tree1.treeModel" fileName="tree1_final.trees">
		<taxa idref="tree1.taxa"/>
	</empiricalTreeDistributionModel>


	<tmrcaStatistic id="tree1.treeModel.rootHeight">
		<mrca>
			<taxa idref="tree1.taxa"/>
		</mrca>
		<treeModel idref="tree1.treeModel"/>
	</tmrcaStatistic>

	<treeLengthStatistic id="tree1.treeLength">
		<treeModel idref="tree1.treeModel"/>
	</treeLengthStatistic>
	

	<tmrcaStatistic id="tree1.age(root)" absolute="true">
		<treeModel idref="tree1.treeModel"/>
	</tmrcaStatistic>

	<strictClockBranchRates id="tree1.state.branchRates">
		<rate>
			<parameter id="tree1.state.clock.rate" value="1.0" lower="0.0"/>
		</rate>
	</strictClockBranchRates>
'
    
    outstr = ""
    for (i in 1:length(names)){
      outstr = paste0(outstr,gsub("tree1",names[[i]],str))
    }
    return(outstr)
  }
  
  
  
  generateOperators <- function(names){
    str = '<operators id="operators" optimizationSchedule="log">

  '
    
    for (i in 1:length(names)){
      str = paste0(str,gsub("tree1",names[[i]],'
                          <empiricalTreeDistributionOperator weight="1">
			<empiricalTreeDistributionModel idref="tree1.treeModel"/>
		</empiricalTreeDistributionOperator>

		<scaleOperator scaleFactor="0.75" weight="1">
			<parameter idref="tree1.state.clock.rate"/>
		</scaleOperator>
		
		<deltaExchange delta="0.75" weight="1">
			<parameter idref="tree1.state.root.frequencies"/>
		</deltaExchange>

'))
      
    }
    str = paste0(str,"</operators>")
    return(str)
  }
  
  
  generateDTA <- function(names, predictor_str){
    str = ""
    
    for (i in 1:length(names)){
      str = paste0(str,gsub("tree1",names[[i]],'
    
	<!-- START Discrete Traits Model                                             -->

	<!-- asymmetric CTMC model for discrete state reconstructions                -->
	<generalSubstitutionModel id="tree1.state.model" randomizeIndicator="false">
		<generalDataType idref="tree1.state.dataType"/>
		<frequencies>
			<frequencyModel id="tree1.state.frequencyModel" normalize="true">
				<generalDataType idref="tree1.state.dataType"/>
				<frequencies>
					<parameter id="tree1.state.frequencies" dimension="10"/>
				</frequencies>
			</frequencyModel>
		</frequencies>

		<!-- rates and indicators                                                    -->
		<rates>
			<parameter id="tree1.state.rates" dimension="90" value="1.0" lower="0.0"/>
		</rates>
		<rateIndicator>
			<parameter id="tree1.state.indicators" dimension="90" value="1.0"/>
		</rateIndicator>
	</generalSubstitutionModel>
	<siteModel id="tree1.state.siteModel">
		<substitutionModel>
			<generalSubstitutionModel idref="tree1.state.model"/>
		</substitutionModel>
	</siteModel>

	<!-- Likelihood for tree given discrete trait data                           -->
	<markovJumpsTreeLikelihood id="tree1.state.treeLikelihood" stateTagName="state" useUniformization="true" saveCompleteHistory="true" logCompleteHistory="true">
		<attributePatterns idref="tree1.state.pattern"/>
		<treeModel idref="tree1.treeModel"/>
		<siteModel idref="tree1.state.siteModel"/>
		<generalSubstitutionModel idref="tree1.state.model"/>
		<strictClockBranchRates idref="tree1.state.branchRates"/>

		<!-- The root state frequencies                                              -->
		<frequencyModel id="tree1.state.root.frequencyModel" normalize="true">
			<generalDataType idref="tree1.state.dataType"/>
			<frequencies>
				<parameter id="tree1.state.root.frequencies" dimension="10"/>
			</frequencies>
		</frequencyModel>

	</markovJumpsTreeLikelihood>
                          '))}
    
    return(str)
  }
  
  generateMCMC <- function(names,subtype,season){
    str = '<mcmc id="mcmc" chainLength="1000000" autoOptimize="true">
		<joint id="joint">
			<prior id="prior">
    
    '
    
    for (i in 1:length(names)){
      str = paste0(str,gsub("tree1",names[[i]],'
        <ctmcScalePrior>
    <ctmcScale>
    <parameter idref="tree1.state.clock.rate"/>
    </ctmcScale>
    <treeModel idref="tree1.treeModel"/>
    </ctmcScalePrior>
    
				<uniformPrior lower="0.0" upper="1.0">
					<parameter idref="tree1.state.frequencies"/>
				</uniformPrior>
				<uniformPrior lower="0.0" upper="1.0">
					<parameter idref="tree1.state.root.frequencies"/>
				</uniformPrior>
                          
        <strictClockBranchRates idref="tree1.state.branchRates"/>
       <generalSubstitutionModel idref="tree1.state.model"/>
 '))
    }
    str = paste0(str,'</prior>
			<likelihood id="likelihood">')
    
    
    for (i in 1:length(names)){
      str = paste0(str,gsub("tree1",names[[i]],'
    				<markovJumpsTreeLikelihood idref="tree1.state.treeLikelihood"/>
    				'
      ))
    }
    str =paste0(str,'</likelihood>		</joint>
		<operators idref="operators"/>
              
              <log id="screenLog" logEvery="10000">
			<column label="Joint" dp="4" width="12">
				<joint idref="joint"/>
			</column>
			<column label="Prior" dp="4" width="12">
				<prior idref="prior"/>
			</column>
			<column label="Likelihood" dp="4" width="12">
				<likelihood idref="likelihood"/>
			</column>
              
                
                ')
    
    for (i in 1:length(names)){
      str = paste0(str,gsub("tree1",names[[i]],'
<column label="tree1.age(root)" sf="6" width="12">
				<tmrcaStatistic idref="tree1.age(root)"/>
			</column>
			<column label="tree1.state.clock.rate" sf="6" width="12">
				<parameter idref="tree1.state.clock.rate"/>
			</column>   
        '
      ))
    }
    str = paste0(str,'</log>
               <log id="fileLog" logEvery="5000" fileName="',subtype,"_",season,'.hhs.geo.log" overwrite="false">
			<joint idref="joint"/>
			<prior idref="prior"/>
			<likelihood idref="likelihood"/>
')
    for (i in 1:length(names)){
      str = paste0(str,gsub("tree1",names[[i]],'
<parameter idref="tree1.treeModel.rootHeight"/>
			<tmrcaStatistic idref="tree1.age(root)"/>
			<treeLengthStatistic idref="tree1.treeLength"/>
			<parameter idref="tree1.state.clock.rate"/>
			<strictClockBranchRates idref="tree1.state.branchRates"/>
						<markovJumpsTreeLikelihood idref="tree1.state.treeLikelihood"/>

			<!-- START Discrete Traits Model                                             -->
			<parameter idref="tree1.state.rates"/>



							'
      ))
    }
    
    str = paste0(str,'</log>


')
    
    for (i in 1:length(names)){
      str = paste0(str,gsub("tree1",names[[i]],'
      
		
<log id="tree1.completeJumpHistory" logEvery="10000" fileName="tree1.hhs.geo.jumpHistory.log">
			<completeHistoryLogger>
				<markovJumpsTreeLikelihood idref="tree1.state.treeLikelihood"/>
			</completeHistoryLogger>
		</log>
		
		<logTree id="tree1.treeFileLog1" logEvery="10000" nexusFormat="true" fileName="tree1.hhs.geo.trees" sortTranslationTable="true">
			<treeModel idref="tree1.treeModel"/>
			<joint idref="joint"/>
			<trait name="state" tag="state">
				<ancestralTreeLikelihood idref="tree1.state.treeLikelihood"/>
			</trait>
		</logTree>

<logTree id="tree1.treeFileLog2" logEvery="5000" nexusFormat="true" fileName="tree1.hhs.geo.history.trees" sortTranslationTable="true">
			<treeModel idref="tree1.treeModel"/>	
			<markovJumpsTreeLikelihood idref="tree1.state.treeLikelihood"/>
		</logTree>
							'
      ))
    }
    str = paste0(str,'
               </mcmc>
               <report>
		<property name="timer">
			<mcmc idref="mcmc"/>
		</property>
	</report>
	
</beast>')
    return(str)
  }
  
  
  generateXML <- function(clusterdata,season,subtype){
    
    names = lapply(clusterdata,function(x)x$cluster)
    taxa = lapply(clusterdata,function(x)x$tips)
    dates = lapply(clusterdata,function(x)x$dates)
    states = lapply(clusterdata,function(x)x$states)
    trees = lapply(clusterdata,function(x)x$tree)
    
    for (i in 1:length(taxa)){
      cluster = gsub("cluster_","",names[[i]])
      tax = mtdt[mtdt$Strain%in%taxa[[i]] & mtdt$Cluster==cluster,]$Strain
      print(tax)
      taxa[[i]] = tax
      dates[[i]] = unlist(lapply(tax,function(x)mtdt[mtdt$Strain==x,]$Date))
      states[[i]] = unlist(lapply(tax,function(x)mtdt[mtdt$Strain==x,]$State))
      state = unlist(lapply(tax,function(x)mtdt[mtdt$Strain==x,]$State))
      state[state=="District Of Columbia"] = "Maryland"
      hhsregions <- c(4,10,9,6,9,8,1,3,4,4,9,10,5,5,7,7,4,6,1,3,1,5,5,4,7,8,7,9,1,2,6,2,4,8,5,6,10,3,1,4,8,4,6,8,1,3,10,3,5,8)
      state = paste0("HHS",hhsregions[match(state,state.name)])
      states[[i]] = state
    }
    
    str = ""
    str = paste0(str,generateHeader())
    for (i in 1:length(names)){
      str = paste0(str,generateTaxa(names[[i]],taxa[[i]],dates[[i]],states[[i]]))
    }
    str = paste0(str,generateTaxonSets(names))
    str = paste0(str,generateTreeModels(names))
    str = paste0(str,generateDTA(names))
    str = paste0(str,generateOperators(names))
    str = paste0(str,generateMCMC(names,subtype,season))
    cat(str,file=paste0("beast_xmls_subsamp/",season,"_",subtype,'/',season,"_",subtype,'_geo_hhs.xml'))
  }
  
  generateXML(clusterdata,season,subtype)
}
